name: 'inspektre code intel'
description: 'Run ApplicationInspector Static Analysis'

inputs:
  location-to-scan:
    description: 'The path relative to repository root to scan.'
    required: true
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.location-to-scan }}
